// Generated by https://quicktype.io

import 'package:flutter/material.dart';
import 'package:komercia_app/features/shared/infrastructure/maps/general.map.dart';

class Menu {
  int idMenu;
  String? codigoMenu;
  String nombreMenu;
  String descripcionMenu;
  String? icono;
  IconData get iconData => iconMap[icono] ?? Icons.help_outline;
  String rutaMenu;
  List<String>? acciones;

  Menu(
      {required this.idMenu,
      this.codigoMenu,
      required this.nombreMenu,
      required this.descripcionMenu,
      required this.icono,
      required this.rutaMenu,
      this.acciones});
}
