// Generated by https://quicktype.io

import 'package:flutter/material.dart';

class Menu {
  int idMenu;
  String codigoMenu;
  String nombreMenu;
  String descripcionMenu;
  IconData icono;
  String rutaMenu;

  Menu({
    required this.idMenu,
    required this.codigoMenu,
    required this.nombreMenu,
    required this.descripcionMenu,
    required this.icono,
    required this.rutaMenu,
  });
}
